name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore SDC_Book_Api
    - name: Build
      run: dotnet build --no-restore SDC_Book_Api
    - name: Test
      run: dotnet test Core.Facts --no-build --verbosity normal 
